# Generated by Django 4.1.1 on 2022-09-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(default="Sem nome", max_length=200)),
                ("video", models.FileField(upload_to="videos/")),
                (
                    "processed_video",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="processed_videos/",
                    ),
                ),
                (
                    "signal",
                    models.FileField(
                        blank=True, default=None, null=True, upload_to="signals/"
                    ),
                ),
                ("thumbnail", models.ImageField(default=None, upload_to="thumbnails/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
