# Generated by Django 4.1.1 on 2022-09-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("YOLOv5", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="plot",
            field=models.FileField(
                blank=True, default=None, null=True, upload_to="plots/"
            ),
        ),
    ]
