# Generated by Django 4.0.2 on 2022-02-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YOLOv5', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='signal',
            field=models.FileField(default='default.csv', upload_to='signals/'),
            preserve_default=False,
        ),
    ]
