# Generated by Django 4.0.2 on 2022-02-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YOLOv5', '0002_video_signal'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='default.jpg', upload_to='thumbnails/'),
            preserve_default=False,
        ),
    ]
