# Generated by Django 4.0.2 on 2022-02-14 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YOLOv5', '0003_video_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='signal',
        ),
        migrations.RemoveField(
            model_name='video',
            name='updated_at',
        ),
    ]
