# Generated by Django 3.2.5 on 2022-02-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YOLOv5', '0004_remove_video_signal_remove_video_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='processed_video',
            field=models.FileField(blank=True, default=None, null=True, upload_to='processed_videos/'),
        ),
        migrations.AddField(
            model_name='video',
            name='signal',
            field=models.FileField(blank=True, default=None, null=True, upload_to='signals/'),
        ),
    ]
