# Generated by Django 4.0.2 on 2022-02-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YOLOv5', '0005_auto_20220214_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.TextField(default='Sem nome', max_length=200),
        ),
    ]
