# Generated by Django 5.0.6 on 2024-06-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Sem nome', max_length=200)),
                ('video', models.FileField(upload_to='videos/')),
                ('processed_video', models.FileField(blank=True, default=None, null=True, upload_to='processed_videos/')),
                ('signal', models.FileField(blank=True, default=None, null=True, upload_to='signals/')),
                ('plot', models.FileField(blank=True, default=None, null=True, upload_to='plots/')),
                ('thumbnail', models.ImageField(default=None, upload_to='thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
